### ISSUE TITLE
Calls to XrmGetResource violate the specification

### ISSUE THREAD

**Issue by Airblader** [dcat/st-xresources#1]
Feel free to close this since Xlib is forgiving enough and I doubt they'd ever introduce such a regression even if Wayland wasn't the focus, but technically the calls to `XrmGetResource` violate the specification. `res_name` and `res_class` are required to have the same number of components, but st-xresources currently always passes two for the former and one for the latter.

Simply passing `NAME` for both name and class would resolve this issue if you don't want to use a proper resource class.

References:
- https://tronche.com/gui/x/xlib/resource-manager/

**Comment by dcat** [comment]
sorry for the late reply, I don't get on github as often as I should.

send me a pull request and I'll merge it.
