### ISSUE TITLE
st-xresources does not automatically update data from Xresources when Xresources is updated

### ISSUE THREAD

**Issue by BombchuLink** [dcat/st-xresources#6]
st-xresources does not automatically update data from Xresources when Xresources is updated. It is required that you close the terminal emulator and re-open it to see the new updates.

How to implement:
#1 got to line 3954 and pull date modified of xresources
#2 go to the for loop at 3997 and check xresources to original pulled date at 3954
#3 call function that sets colours from xresources inside of the checking if statement
#4 ????
#5 profit

I've managed to do step 1...

```
	struct tm *timeinit;
	struct tm *timenow;
	struct stat attrib;
	/* Get last-modified time of Xresources*/
	stat("~/.config/Xresources", &attrib);
	timeinit = localtime(&(attrib.st_ctime));
```
and 2
```
		/* Check if Xresources was changed since init*/
		stat("~/.config/Xresources", &attrib);
		timenow = localtime(&(attrib.st_ctime));
		if (timeinit->tm_year != timenow->tm_year ||
			timeinit->tm_mon  != timenow->tm_mon  ||
			timeinit->tm_mday != timenow->tm_mday ||
			timeinit->tm_hour != timenow->tm_hour ||
			timeinit->tm_min  != timenow->tm_min
			){
			printf("XRESOURCES IS OUTDATED\n");
			timeinit->tm_year = timenow->tm_year;
			timeinit->tm_mon  = timenow->tm_mon;
			timeinit->tm_mday = timenow->tm_mday;
			timeinit->tm_hour = timenow->tm_hour;
			timeinit->tm_min  = timenow->tm_min;
		}
		else {
			printf("XResources is up to date\n");
		}
```
however with this method it does put a dependency on ``<sys/stat.h>`` and ``<time.h>`` 

as for step 3... I can't seem to actually get any ground with this one. I'm probably just being stupid but ``xloadcols()`` ``xinit()``, and even changing xw.cmap doesn't seem to get it to re-load the Xresources assets at any point, and thus I'm at a dead end.

I'm very sorry to have bothered you with this if it's not something you're willing to look into or care about. I know it's been 5 years since the last push to this repo but I don't know where else to look really. I've spend days trying to figure this issue out at this point.

Also from what (limited) information I can find, no other terminal does this, so I guess nobody has bothered to make this a thing before?

**Comment by dcat** [comment]
neeasade took over the torch on this project a while ago, file a push request if it doesn't already exist in https://github.com/gnotclub/xst

**Comment by BombchuLink** [comment]
Ah, sorry about that. I'll head on over there. 

Thanks for pointing me in the correct direction.
