### ISSUE TITLE
Issue with font settings

### ISSUE THREAD

**Issue by m00nwtchr** [dcat/st-xresources#7]
I'm trying to set my font in the `.Xresources`, i kept the font variable in my `config.h` as the default (Liberation Sans).
Loading colors and stuff works, but when i put `st.font: Hack:pixelsize=14:antialias=true:autohint=true` in my .Xresources neofetch still shows `Liberation Sans` as the Terminal Font.
(yes i did restart it and i did load the new Xresources via `xrdb`)

Help would be appreciated

**Comment by dcat** [comment]
this repo is no longer being maintained, check out the [gnotclub/xst](https://github.com/gnotclub/xst) fork.
